# ????????????? IDEA ????
archetype.groupId=com.nedk.framework
archetype.artifactId=nedk-framework-archetype
archetype.version=1.0.0

# ?????? IDE ????????
excludePatterns=archetype.properties,*.iml,.idea/,logs/

# ????? gitignore
gitignore=.gitignore