server:
  port: ${serverPort}  # 动态端口

spring:
  application:
    name: ${serverName} # 动态应用名
  datasource:
    # 也可以把数据库名变成变量，比如 benefit_db 改成 ${dbName}，这里先保持简单
    url: jdbc:mysql://localhost:3306/ ${dbName}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # ... 其他配置保持不变
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 访问路径
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs